version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/genealogic-tree-front"
    schedule:
      interval: "weekly"
    labels: 
      - "npm dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
