version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/genealogic-tree-front"
    schedule:
      interval: "daily"
    labels:
      - "npm dependencies"
    reviewers:
      - "Adamou02"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
