name: Node.js CI

on:
  pull_request:
    branches: 
      - main
      - pre-main

jobs:


  ubuntu-build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./genealogic-tree-front

    steps:
    - uses: actions/checkout@v3
    - name: Use the lastest version of Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test


  windows-build:

    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: ./genealogic-tree-front

    steps:
    - uses: actions/checkout@v3
    - name: Use the lastest version of Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
